//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasServiceApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GasServiceCenterEntities : DbContext
    {
        private static GasServiceCenterEntities _context;
        public GasServiceCenterEntities()
            : base("name=GasServiceCenterEntities")
        {
        }
        public static GasServiceCenterEntities GetContext()
        {
            if (_context == null)
                _context = new GasServiceCenterEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GasMeters> GasMeters { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceRequestHistory> ServiceRequestHistory { get; set; }
        public virtual DbSet<ServiceRequests> ServiceRequests { get; set; }
        public virtual DbSet<StatusRequestHistory> StatusRequestHistory { get; set; }
        public virtual DbSet<StatusServiceRequests> StatusServiceRequests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserActions> UserActions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VerifedStatus> VerifedStatus { get; set; }
    }
}
