//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasServiceApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasMeters
    {
        public int GasMeterID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> LastReadDate { get; set; }
        public Nullable<decimal> LastReadValue { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
