//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasServiceApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequests()
        {
            this.ServiceRequestHistory = new HashSet<ServiceRequestHistory>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string AssignedTo { get; set; }
        public string Priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestHistory> ServiceRequestHistory { get; set; }
        public virtual StatusServiceRequests StatusServiceRequests { get; set; }
        public virtual Users Users { get; set; }
    }
}
